config/routes.rb
Rails.application.routes.draw do
  mount GraphiQL::Rails::Engine, at: '/graphiql', graphql_path: '/graphql' if Rails.env.development?
  post '/graphql', to: 'graphql#execute'

  concern :csv_importable do
    collection do
      get :export_csv
      post :import_csv
    end
  end

  resources :prayers
  resources :events
  resources :landing

  devise_for :masjids, path: 'masjids', controllers: {
    sessions: 'masjids/sessions',
    registrations: 'masjids/registrations'
  }
  resources :masjids, param: :slug do
    resources :payouts, only: %i[new create]
    resources :dashboard, only: %i[index get]
    member do
      get :connect_stripe
      get :open_stripe_dashboard
    end
  end

  resources :fundraisers, param: :slug do
    member do
      patch :toggle_active
    end
  end

  resources :pledges, concerns: :csv_importable
  resources :contacts, concerns: :csv_importable
  resources :donations, concerns: :csv_importable
  resources :revenues, concerns: :csv_importable
  resources :expenses, concerns: :csv_importable

  resources :months do
    collection do
      get :months
    end
  end

  resources :options do
    collection do
      get :pledges
    end
  end

  post '/webhooks/stripe', to: 'webhooks#stripe'

  resources :bulk_deletes, only: [] do
    collection do
      delete :expenses_and_revenues
      delete :pledges
      delete :contacts
      delete :donations
    end
  end

  resources :notifications, only: %i[index] do
    collection do
      patch :mark_as_read
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'landing#index'
end

app/models/fundraiser.rb
require 'rqrcode'
class Fundraiser < ApplicationRecord
  extend FriendlyId

  belongs_to :masjid
  has_many :donations, dependent: :restrict_with_error
  has_many :pledges, dependent: :restrict_with_error
  has_one_attached :qr_code

  after_create_commit :generate_qr_code
  after_destroy :delete_qr_code_from_s3
  after_create :regenerate_slug_with_id

  validates :name, presence: true
  validates :description, presence: true
  validates :goal_amount, presence: true, numericality: { greater_than_or_equal_to: 0 }

  scope :active, -> { where(active: true) }

  friendly_id :slug_candidates, use: [:slugged, :finders]

  def slug_candidates
    [
      %i[name id]
    ]
  end

  def should_generate_new_friendly_id?
    slug.blank? || name_changed?
  end

  def regenerate_slug_with_id
    return unless slug.present? && !slug.match?(/\d+$/) # If the slug is missing an ID

    update(slug: nil) # Forces FriendlyId to regenerate the slug
    save!
  end

  def self.ransackable_attributes(_auth_object = nil)
    ['name']
  end

  private

  def generate_qr_code
    fundraiser_url = "https://mobile.mymasjidhub.com/masjids/#{masjid.slug}/fundraisers/#{slug}"
    qr = RQRCode::QRCode.new(fundraiser_url)

    qr_png = StringIO.new(qr.as_png(size: 300, border_modules: 2).to_s)

    qr_code.attach(
      io: qr_png,
      filename: "fundraiser-#{name}.png",
      content_type: 'image/png'
    )
  end

  def delete_qr_code_from_s3
    # Only delete if qr_code is attached
    qr_code.purge_later if qr_code.attached?
  end
end

app/controllers/fundraisers_controller.rb
class FundraisersController < ApplicationController
  before_action :authenticate_masjid!
  before_action :set_fundraiser, only: %i[show edit update destroy]
  include Pagy::Backend
  Pagy::DEFAULT[:limit] = 25

  # GET /fundraisers or /fundraisers.json
  def index
    @fundraisers = current_masjid.fundraisers
  end

  # GET /fundraisers/1 or /fundraisers/1.json
  def show
    donations = @fundraiser.donations.order(created_at: 'desc')

    @q = donations.ransack(params[:q])
    donations = @q.result.includes(:contact, :fundraiser)
    @pagy, @table_donations = pagy(donations)
  end

  # GET /fundraisers/new
  def new
    @fundraiser = Fundraiser.new
  end

  # GET /fundraisers/1/edit
  def edit; end

  # POST /fundraisers or /fundraisers.json
  def create
    @fundraiser = Fundraiser.new(fundraiser_params)
    @fundraiser.masjid_id = current_masjid.id

    respond_to do |format|
      if @fundraiser.save
        format.html { redirect_to fundraiser_url(@fundraiser), notice: 'Fundraiser was successfully created.' }
        format.turbo_stream do
          render turbo_stream: [turbo_stream.prepend('fundraisers', partial: 'fundraisers/fundraiser',
                                                                    locals: { fundraiser: @fundraiser }),
                                turbo_stream.replace('flash',
                                                     partial: 'shared/alert', locals: { notice: 'Fundraiser was successfully created.' })]
        end
        format.json { render :show, status: :created, location: @fundraiser }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @fundraiser.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fundraisers/1 or /fundraisers/1.json
  def update
    respond_to do |format|
      if @fundraiser.update(fundraiser_params)
        format.turbo_stream do
          render turbo_stream: [turbo_stream.replace("detail_#{@fundraiser.id}", partial: 'fundraisers/detail',
                                                                                 locals: { fundraiser: @fundraiser }),
                                turbo_stream.replace('flash',
                                                     partial: 'shared/alert', locals: { notice: 'Fundraiser was successfully edited.' })]
        end
        format.html { redirect_to fundraiser_url(@fundraiser), notice: 'Fundraiser was successfully updated.' }
        format.json { render :show, status: :ok, location: @fundraiser }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @fundraiser.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fundraisers/1 or /fundraisers/1.json
  def destroy
    if @fundraiser.destroy

      respond_to do |format|
        format.html { redirect_to fundraisers_url, notice: 'Fundraiser was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace('flash',
                                                    partial: 'shared/error', locals:
                                                     { notice: 'Error: Please remove the linked pledges/donations.' })
        end
      end
    end
  end

  def toggle_active
    @fundraiser = Fundraiser.find(params[:id])
    Rails.logger.debug 'Toggling fundraiser active'

    @fundraiser.update(active: !@fundraiser.active)

    Rails.logger.debug "Fundraiser after patch #{@fundraiser.active}"

    notice = @fundraiser.active ? 'Fundraiser was set to active.' : 'Fundraiser was set to inactive.'

    respond_to do |format|
      format.html { redirect_to fundraiser_path(@fundraiser), notice: notice }
      format.turbo_stream do
        render turbo_stream: [turbo_stream.replace('flash',
                                                   partial: 'shared/alert', locals:
                                                    { notice: notice }),
                              turbo_stream.replace('toggle',
                                                   partial: 'fundraisers/toggle_button', locals:
                                                    { fundraiser: @fundraiser })]
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_fundraiser
    @fundraiser = Fundraiser.find(params[:slug])
  end

  # Only allow a list of trusted parameters through.
  def fundraiser_params
    params.require(:fundraiser).permit(:name, :description, :goal_amount, :masjid_id, :end_date)
  end
end

app/helpers/fundraisers_helper.rb
module FundraisersHelper
  def qr_code_url(fundraiser)
    rails_blob_url(fundraiser.qr_code, disposition: 'inline') if fundraiser.qr_code.attached?
  end
end

app/views/fundraisers/_detail.html.erb
<div id="detail_<%= fundraiser.id %>">
  <dl class="p-4 h-full bg-gray-50 rounded-lg border border-gray-200 dark:bg-gray-700 dark:border-gray-600">
    <h2 class="flex items-center mb-4 text-xl font-bold leading-none text-gray-900 sm:text-2xl dark:text-white sm:mb-5">
      <%= fundraiser.name %>
    </h2>
    <dt class="mb-2 leading-none text-gray-500 dark:text-gray-400">Goal Amount</dt>
    <dd class="mb-4 font-medium text-gray-900 sm:mb-5 dark:text-white"><%= number_to_currency(fundraiser.goal_amount) %></dd>
    <dt class="mb-2 leading-none text-gray-500 dark:text-gray-400">Description</dt>
    <dd class="mb-4 font-medium text-gray-900 sm:mb-5 dark:text-white"><%= fundraiser.description %></dd>
    <dt class="mb-2 leading-none text-gray-500 dark:text-gray-400">Donations Made / Amount Donated</dt>
    <dd class="mb-4 font-medium text-gray-900 sm:mb-5 dark:text-white"><%="#{fundraiser.donations.count} / #{number_to_currency(fundraiser.donations.sum(:amount))}" %></dd>
    <dt class="mb-2 leading-none text-gray-500 dark:text-gray-400">Pledges Made / Amount Pledged</dt>
    <dd class="mb-4 font-medium text-gray-900 sm:mb-5 dark:text-white"><%= "#{fundraiser.pledges.count} / #{number_to_currency(fundraiser.pledges.sum(:amount))}" %></dd>
  </dl>
</div>

app/views/fundraisers/_form.html.erb
<%= form_with(model: fundraiser, class: "p-4 md:p-5") do |form| %>
  <% if fundraiser.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(fundraiser.errors.count, "error") %> prohibited this fundraiser from being saved:</h2>
      <ul>
        <% fundraiser.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="grid gap-4 mb-4 grid-cols-2">
    <div class="col-span-2">
      <%= form.label :name, "Fundraiser Name*", class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white"%>
      <%= form.text_field :name, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500", placeholder: "Enter a fundraiser name", required: true %>
    </div>
     <div class="col-span-2">
      <%= form.label :description, "Fundraiser Description*", class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white"%>
      <%= form.text_area :description, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500", placeholder: "Enter a description", required: true %>
    </div>
    <div class="col-span-2 sm:col-span-1">
      <%= form.label :goal_amount, "Goal Amount*", class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white"%>
      <%= form.number_field :goal_amount, step: 0.01, min: 0.01, class:"bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500", placeholder: "$20,000", required: true %>
    </div>
    <div class="col-span-2 sm:col-span-1">
      <%= form.label :end_date, "End Date", class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white"%>
      <%= form.date_field :end_date, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500", placeholder: "09/15/2024" %>
    </div>
    <button type="submit" class="text-white inline-flex items-center bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
      Submit
    </button>
  </div>
<% end %>

app/views/fundraisers/_fundraiser.html.erb
<div id="<%= fundraiser %>">
  <% progress = [fundraiser.donations.sum(:amount) / fundraiser.goal_amount * 100, 100].min %>
  <div class="rounded-lg h-full border border-gray-200 bg-white p-6 shadow-sm dark:border-gray-700 dark:bg-gray-800">
    <div class="pt-6">
      <div class="flex items-center justify-between gap-1">
        <%= link_to fundraiser.name, fundraiser, class: "text-lg font-semibold leading-tight text-gray-900 hover:underline dark:text-white" %>
      </div>
      <p class="font-normal text-gray-700 dark:text-gray-400"><%= fundraiser.description %></p>
      <div class="mt-2 flex items-center gap-2">
        <div class="w-full bg-gray-200 rounded-full h-2.5 dark:bg-gray-700">
          <div class="bg-green-400 h-2.5 rounded-full" style="width: <%= progress %>% ; min-width: <%= progress > 0 ? '10px' : '0px' %>;">
          </div>
        </div>
        <p class="text-sm font-medium text-gray-900 dark:text-white"><%= number_to_currency(fundraiser.goal_amount) %></p>
      </div>
      <div class="mt-4 flex items-center justify-between gap-4">
        <p class="tfont-normal text-gray-700 dark:text-gray-400">Raised Amount</p>
        <p class="text-1xl font-extrabold leading-tight text-gray-900 dark:text-white"><%= number_to_currency(fundraiser.donations.sum(:amount)) %></p>
      </div>
      <div class="mt-4 flex items-center justify-between gap-4">
        <p class="tfont-normal text-gray-700 dark:text-gray-400">Created At</p>
        <p class="text-1xl font-extrabold leading-tight text-gray-900 dark:text-white"><%= fundraiser.created_at.strftime("%b %d, %Y") %></p>
      </div>
    </div>
  </div>
</div>

app/views/fundraisers/_toggle_button.html.erb
 <%= button_to (@fundraiser.active? ? "Active" : "Inactive"),  toggle_active_fundraiser_path(fundraiser), method: :patch, id: "toggle", class: 
                                "py-2.5 px-5 text-sm font-medium focus:outline-none rounded-lg border focus:z-10 focus:ring-4 " + (fundraiser.active? ? 
                                "text-white bg-green-500 border-green-600 hover:bg-green-600 focus:ring-green-300" :
                                "text-gray-900 bg-white border-gray-200 hover:bg-gray-100 hover:text-blue-700 focus:ring-gray-200 dark:focus:ring-gray-700 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700") %>

app/views/fundraisers/edit.html.erb
<%= turbo_frame_tag "turbo-modal" do %>
  <div class = "turbo-modal">
    <%= tag.div data: { controller: "turbo-modal", action: "turbo:submit-end->turbo-modal#submitEnd" } do %>
      <div class="relative p-4 w-full max-w-md max-h-full">
        <!-- Modal content -->
        <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
          <!-- Modal header -->
          <div class="flex items-center justify-between p-4 md:p-5 border-b rounded-t dark:border-gray-600">
            <h3 class="text-lg font-semibold text-gray-900 dark:text-white">
              Edit Fundraiser
            </h3>
            <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ms-auto inline-flex justify-center items-center dark:hover:bg-gray-600 dark:hover:text-white">
              <%= link_to 'Close', 
                "#", data: {
                      controller: "turbo-modal",
                      action: "turbo-modal#close"
                    } %>
              <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
              </svg>
              <span class="sr-only">Close modal</span>
            </button>
          </div>
          <!-- Modal body -->
          <%= render "form", fundraiser: @fundraiser %>
        </div>
      </div>
    <% end  %>
  </div>
<% end  %>

app/views/fundraisers/index.html.erb
<div class="antialiased">
  <section class="p-4 md:ml-64 h-auto pt-20">
    <% content_for :title, "Fundraisers" %>
    <div class="flex justify-between items-center">
      <h1 class="mb-4 text-4xl tracking-tight font-extrabold text-gray-900 dark:text-white">Fundraisers</h1>
    </div>
    <div id="fundraisers" class="mb-4 grid gap-4 sm:grid-cols-2 md:mb-8 lg:grid-cols-3 xl:grid-cols-4">
      <% @fundraisers.each do |fundraiser| %>
        <%= render fundraiser %>
      <% end %>
    </div>
  </section>
</div>

app/views/fundraisers/new.html.erb
<%= turbo_frame_tag "turbo-modal" do %>
  <div class = "turbo-modal">
    <%= tag.div data: { controller: "turbo-modal", action: "turbo:submit-end->turbo-modal#submitEnd" } do %>
      <div class="relative p-4 w-full max-w-md max-h-full">
        <!-- Modal content -->
        <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
          <!-- Modal header -->
          <div class="flex items-center justify-between p-4 md:p-5 border-b rounded-t dark:border-gray-600">
            <h3 class="text-lg font-semibold text-gray-900 dark:text-white">
              Add New Fundraiser
            </h3>
            <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ms-auto inline-flex justify-center items-center dark:hover:bg-gray-600 dark:hover:text-white"
            data-controller="turbo-modal"
            data-action="turbo-modal#close">
      <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
      </svg>
              <span class="sr-only">Close modal</span>
            </button>
          </div>
          <!-- Modal body -->
          <%= render "form", fundraiser: @fundraiser %>
        </div>
      </div>
    <% end  %>
  </div>
<% end  %>

app/views/fundraisers/show.html.erb
<div class="antialiased">
  <section class="p-4 md:ml-64 h-auto pt-20">
    <div class="flex justify-between items-center">
      <h1 class="mb-4 text-4xl tracking-tight font-extrabold text-gray-900 dark:text-white">Fundraiser Details</h1>
    </div>
    <div class="py-8 mx-auto w-full">
      <div class="grid gap-4 px-4 mb-4 sm:mb-5 sm:grid-cols-2 sm:gap-6 md:gap-12">
        <!-- Column -->
        <%= render "detail", fundraiser: @fundraiser %>
        <!-- Column -->
        <dl class="p-4 bg-gray-50 rounded-lg border border-gray-200 dark:bg-gray-700 dark:border-gray-600">
          <dt class="mb-2 font-semibold leading-none text-gray-900 dark:text-white">QR Code</dt>
          <% if @fundraiser.qr_code.attached? %>
            <%= image_tag qr_code_url(@fundraiser), alt: "Fundraiser QR Code" if @fundraiser.qr_code.attached? %>
            <dd class="font-light text-gray-500 dark:text-gray-400 py-2">
              <%= link_to "Click here to visit fundraiser.", "https://mobile.mymasjidhub.com/masjids/#{current_masjid.slug}/fundraisers/#{@fundraiser.slug}" %>
            </dd>
          <% else %>
            <dd class="font-light text-gray-500 dark:text-gray-400">
              QR Code is not available yet.
            </dd>
          <% end %>
        </dl>
      </div>
      <div id="donations" class="py-4 px-4 mx-auto border-gray-300 dark:border-gray-600 rounded-xl h-128">
        <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
          <%= render "tables/donation_table",  table: @table_donations, query: @q, pagy: @pagy, model: :donation %>
        </div>
      </div>
      <div class="flex items-center py-4 px-4 space-x-4">
        <% if @fundraiser.qr_code.attached? %>
          <%= link_to "Download QR Code", rails_blob_path(@fundraiser.qr_code, disposition: "attachment"), class: "py-2.5 px-5 text-sm font-medium text-gray-900 focus:outline-none bg-white rounded-lg border border-gray-200 hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-700 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700" %>
        <% end %>
        <%= link_to "Back to Fundraisers", fundraisers_path, class: "py-2.5 px-5 text-sm font-medium text-gray-900 focus:outline-none bg-white rounded-lg border border-gray-200 hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-700 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700" %>
        <%= link_to edit_fundraiser_path(@fundraiser), data: { turbo_frame: "turbo-modal" } do %>
          <button type="button" class="inline-flex items-center py-2.5 px-5 text-sm font-medium text-gray-900 focus:outline-none bg-white rounded-lg border border-gray-200 hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-700 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700">
            <svg aria-hidden="true" class="mr-1 -ml-1 w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M17.414 2.586a2 2 0 00-2.828 0L7 10.172V13h2.828l7.586-7.586a2 2 0 000-2.828z"></path><path fill-rule="evenodd" d="M2 6a2 2 0 012-2h4a1 1 0 010 2H4v10h10v-4a1 1 0 112 0v4a2 2 0 01-2 2H4a2 2 0 01-2-2V6z" clip-rule="evenodd"></path></svg>
            Edit
          </button>
        <%  end %>
        <%= render "toggle_button", fundraiser: @fundraiser %>
        <%= link_to @fundraiser, id: @fundraiser.id, data: { turbo_method: :delete, turbo_confirm: 'Are you sure you want to delete this item?'} do %>
          <button type="button" class="inline-flex items-center text-white bg-red-600 hover:bg-red-700 focus:ring-4 focus:outline-none focus:ring-red-300 font-medium rounded-lg border border-gray-200 dark:border-gray-600 text-sm py-2.5 px-5 text-center dark:bg-red-500 dark:hover:bg-red-600 dark:focus:ring-red-900">
            <svg aria-hidden="true" class="w-5 h-5 mr-1.5 -ml-1" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd"></path></svg>
            Delete
          </button>
        <% end %>
      </div>
    </div>
  </section>
</div>