config/routes.rb
Rails.application.routes.draw do
  mount GraphiQL::Rails::Engine, at: '/graphiql', graphql_path: '/graphql' if Rails.env.development?
  post '/graphql', to: 'graphql#execute'

  concern :csv_importable do
    collection do
      get :export_csv
      post :import_csv
    end
  end

  resources :prayers
  resources :events
  resources :landing

  devise_for :masjids, path: 'masjids', controllers: {
    sessions: 'masjids/sessions',
    registrations: 'masjids/registrations'
  }
  resources :masjids, param: :slug do
    resources :payouts, only: %i[new create]
    resources :dashboard, only: %i[index get]
    member do
      get :connect_stripe
      get :open_stripe_dashboard
    end
  end

  resources :fundraisers, param: :slug do
    member do
      patch :toggle_active
    end
  end

  resources :pledges, concerns: :csv_importable
  resources :contacts, concerns: :csv_importable
  resources :donations, concerns: :csv_importable
  resources :revenues, concerns: :csv_importable
  resources :expenses, concerns: :csv_importable

  resources :months do
    collection do
      get :months
    end
  end

  resources :options do
    collection do
      get :pledges
    end
  end

  post '/webhooks/stripe', to: 'webhooks#stripe'

  resources :bulk_deletes, only: [] do
    collection do
      delete :expenses_and_revenues
      delete :pledges
      delete :contacts
      delete :donations
    end
  end

  resources :notifications, only: %i[index] do
    collection do
      patch :mark_as_read
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'landing#index'
end

app/views/sidebar/_sidebar.html.erb
<aside
  class="fixed top-0 left-0 z-40 w-64 h-screen transition-transform duration-300 bg-white border-r border-gray-200 md:translate-x-0 dark:bg-gray-800 dark:border-gray-700"
  data-collapsed="false"
  aria-label="Sidenav"
  id="drawer-navigation"
>
  <div class="overflow-y-auto py-5 px-3 h-full bg-white dark:bg-gray-800">
    <ul class="space-y-2">
      <li class="flex justify-left -mb-6">
        <%= link_to root_path do %>
          <img
            src="/assets/myMasjidHub_LogoFiles_dark.svg"
            class="h-28 block dark:hidden"
            alt="MasjidManager Logo"
          />
          <img
            src="/assets/myMasjidHub_LogoFiles.svg"
            class="h-28 hidden dark:block"
            alt="MasjidManager Logo"
          />
        <% end %>
      </li>
      <li class="text-left">
        <span class="text-gray-400 dark:text-white text-xs"><%= current_masjid.name %></span>
      </li>
      <li>
        <button
          type="button"
          class="text-white bg-blue-700 w-full hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800"
          id="user-add-button"
          aria-expanded="false"
          data-dropdown-toggle="dropdown-adds"
        >
          <span class="sr-only">Open add menu</span>
          Add +
        </button>
        <!-- Dropdown-adds menu -->
        <div
          class="hidden z-50 my-4 w-56 text-base list-none bg-white rounded divide-y divide-gray-100 shadow dark:bg-gray-700 dark:divide-gray-600 rounded-xl"
          id="dropdown-adds"
        >
          <div class="py-3 px-4">
            <span
              class="block text-sm text-gray-900 truncate dark:text-white"
            >Add records for your masjid</span>
          </div>
          <ul
            class="py-1 text-gray-700 dark:text-gray-300"
            aria-labelledby="dropdown-adds"
          >
            <li>
              <%= link_to new_expense_path,  data: { turbo_frame: "turbo-modal"} do %>
                <p class="block py-2 px-4 text-sm hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-400 dark:hover:text-white">
                  Add Expense
                </p>
              <% end %>
            </li>
            <li>
              <%= link_to new_revenue_path,  data: { turbo_frame: "turbo-modal"} do %>
                <p class="block py-2 px-4 text-sm hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-400 dark:hover:text-white">
                  Add Revenue
                </p>
              <% end %>
            </li>
            <li>
              <%= link_to new_donation_path,  data: { turbo_frame: "turbo-modal"} do %>
                <p class="block py-2 px-4 text-sm hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-400 dark:hover:text-white">
                  Add Donation
                </p>
              <% end %>
            </li>
            <li>
              <%= link_to new_fundraiser_path,  data: { turbo_frame: "turbo-modal"} do %>
                <p class="block py-2 px-4 text-sm hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-400 dark:hover:text-white">
                  Add Fundraiser
                </p>
              <% end %>
            </li>
            <li>
              <%= link_to new_pledge_path,  data: { turbo_frame: "turbo-modal"} do %>
                <p class="block py-2 px-4 text-sm hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-400 dark:hover:text-white">
                  Add Pledge
                </p>
              <% end %>
            </li>
          </ul>
          <ul
            class="py-1 text-gray-700 dark:text-gray-300"
            aria-labelledby="dropdown-adds"
          >
            <li>
              <%= link_to new_contact_path,  data: { turbo_frame: "turbo-modal"} do %>
                <p class="block py-2 px-4 text-sm hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-400 dark:hover:text-white">
                  Add Contact
                </p>
              <% end %>
            </li>
            <li>
              <%= link_to new_prayer_path,  data: { turbo_frame: "turbo-modal"} do %>
                <p class="block py-2 px-4 text-sm hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-400 dark:hover:text-white">
                  Add Prayer
                </p>
              <% end %>
            </li>
            <li>
              <%= link_to new_event_path,  data: { turbo_frame: "turbo-modal"} do %>
                <p class="block py-2 px-4 text-sm hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-400 dark:hover:text-white">
                  Add Event
                </p>
              <% end %>
            </li>
          </ul>
        </div>
      </li>
      <li>
        <a
          href="/masjids/<%=current_masjid.id %>/dashboard"
          class="flex items-center p-2 text-base font-medium text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group"
        >
          <svg
            class="w-6 h-6 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white"
            fill="currentColor"
            viewBox="0 0 20 20"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path d="M2 10a8 8 0 018-8v8h8a8 8 0 11-16 0z"></path>
            <path d="M12 2.252A8.014 8.014 0 0117.748 8H12V2.252z"></path>
          </svg>
          <span class="ml-3">Home</span>
        </a>
      </li>
      <li>
        <button
          type="button"
          class="flex items-center p-2 w-full text-base font-medium text-gray-900 rounded-lg transition duration-75 group hover:bg-gray-100 dark:text-white dark:hover:bg-gray-700"
          aria-controls="dropdown-pages"
          data-collapse-toggle="dropdown-pages"
        >
          <svg
            class="flex-shrink-0 w-6 h-6 text-gray-500 transition duration-75 group-hover:text-gray-900 dark:text-gray-400 dark:group-hover:text-white"
            fill="currentColor"
            viewBox="0 0 20 20"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              fill-rule="evenodd"
              d="M4 4a2 2 0 012-2h4.586A2 2 0 0112 2.586L15.414 6A2 2 0 0116 7.414V16a2 2 0 01-2 2H6a2 2 0 01-2-2V4zm2 6a1 1 0 011-1h6a1 1 0 110 2H7a1 1 0 01-1-1zm1 3a1 1 0 100 2h6a1 1 0 100-2H7z"
              clip-rule="evenodd"
            ></path>
          </svg>
          <span class="flex-1 ml-3 text-left whitespace-nowrap">Financials</span>
          <svg
            class="w-6 h-6"
            fill="currentColor"
            viewBox="0 0 20 20"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              fill-rule="evenodd"
              d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
              clip-rule="evenodd"
            ></path>
          </svg>
        </button>
        <ul id="dropdown-pages" class="hidden py-2 space-y-2">
          <li>
            <a
              href="/expenses"
              class="flex items-center p-2 pl-11 w-full text-base font-medium text-gray-900 rounded-lg transition duration-75 group hover:bg-gray-100 dark:text-white dark:hover:bg-gray-700"
            >Expenses</a>
          </li>
          <li>
            <a
              href="/revenues"
              class="flex items-center p-2 pl-11 w-full text-base font-medium text-gray-900 rounded-lg transition duration-75 group hover:bg-gray-100 dark:text-white dark:hover:bg-gray-700"
            >Revenues</a>
          </li>
          <li>
            <a
              href="/donations"
              class="flex items-center p-2 pl-11 w-full text-base font-medium text-gray-900 rounded-lg transition duration-75 group hover:bg-gray-100 dark:text-white dark:hover:bg-gray-700"
            >Donations</a>
          </li>
          <li>
            <a
              href="/pledges"
              class="flex items-center p-2 pl-11 w-full text-base font-medium text-gray-900 rounded-lg transition duration-75 group hover:bg-gray-100 dark:text-white dark:hover:bg-gray-700"
            >Pledges</a>
          </li>
          <li>
            <a
              href="/fundraisers"
              class="flex items-center p-2 pl-11 w-full text-base font-medium text-gray-900 rounded-lg transition duration-75 group hover:bg-gray-100 dark:text-white dark:hover:bg-gray-700"
            >Fundraisers</a>
          </li>
        </ul>
      </li>
      <li>
        <button
          type="button"
          class="flex items-center p-2 w-full text-base font-medium text-gray-900 rounded-lg transition duration-75 group hover:bg-gray-100 dark:text-white dark:hover:bg-gray-700"
          aria-controls="dropdown-sales"
          data-collapse-toggle="dropdown-sales"
        >
          <svg class="w-6 h-6" fill="currentColor" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 4h12M6 4v16M6 4H5m13 0v16m0-16h1m-1 16H6m12 0h1M6 20H5M9 7h1v1H9V7Zm5 0h1v1h-1V7Zm-5 4h1v1H9v-1Zm5 0h1v1h-1v-1Zm-3 4h2a1 1 0 0 1 1 1v4h-4v-4a1 1 0 0 1 1-1Z"/>
          </svg>
          <span class="flex-1 ml-3 text-left whitespace-nowrap">Masjid</span>
          <svg
            class="w-6 h-6"
            fill="currentColor"
            viewBox="0 0 20 20"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              fill-rule="evenodd"
              d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
              clip-rule="evenodd"
            ></path>
          </svg>
        </button>
        <ul id="dropdown-sales" class="hidden py-2 space-y-2">
          <li>
            <a
              href="/events"
              class="flex items-center p-2 pl-11 w-full text-base font-medium text-gray-900 rounded-lg transition duration-75 group hover:bg-gray-100 dark:text-white dark:hover:bg-gray-700"
            >Events</a>
          </li>
       
          <li>
            <a
              href="/contacts"
              class="flex items-center p-2 pl-11 w-full text-base font-medium text-gray-900 rounded-lg transition duration-75 group hover:bg-gray-100 dark:text-white dark:hover:bg-gray-700"
            >Contacts</a>
          </li>
        </ul>
      </li>
    </ul>
  </div>
</aside>